#!/usr/bin//env python3

import json

j               = open('finances.json')
financeWeeks    = json.load(j)['data']

out = []

for week in financeWeeks:
    for obj in financeWeeks[week]['__collections__']:
        if obj == 'daily-totals':
            for day in financeWeeks[week]['__collections__'][obj]:
                temp = []
                for thing in financeWeeks[week]['__collections__'][obj][day]:
                    temp.append(financeWeeks[week]['__collections__'][obj][day][thing])
                out.append(temp)

with open("financeAdj.json", "w") as outfile:
    json.dump(out, outfile)