#!/usr/bin//env python3

import json

j               = open('finances.json')
financeWeeks    = json.load(j)['data']

financesOut = []
schedOut    = []

for week in financeWeeks:
    for obj in financeWeeks[week]['__collections__']:
        if obj == 'store-runs':
            for day in financeWeeks[week]['__collections__'][obj]:
                temp = []
                for thing in financeWeeks[week]['__collections__'][obj][day]:
                    temp.append(financeWeeks[week]['__collections__'][obj][day][thing])
                financesOut.append(temp)

with open("financeAdj.json", "w") as outfile:
    json.dump(financesOut, outfile)